### ISSUE TITLE
VisoInfo.h missing

### ISSUE THREAD

**Issue by tonystark12** [ZhuangYanDLUT/dlut_vision#3]
I got the following error while trying to catkin_make the packages

fatal error: viso2_ros/VisoInfo.h: No such file or directory
 #include <viso2_ros/VisoInfo.h>

Is this file missing?

**Comment by tonystark12** [comment]
was able to solve it, by renaming the folder in devel/include/dlut_viso2_ros to viso2_ros, but new issues surfaced after that, addressed in the next issue.

**Comment by ZhuangYanDLUT** [comment]
乃亮，

问题好像解决了，管理员好像重命名了。

以后管理文件的时候注意这个问题就可以了吧？

庄严

---

Professor Yan Zhuang
School of Control Science and Engineering
Dalian University of Technology
Dalian, 116024, China
Email: zhuang@dlut.edu.cn
Tel: 86-411-84707581
Fax: 86-411-84707581

**Comment by tonystark12** [comment]
Thanks for your reply, but I dont read Chinese.

**Comment by ZhuangYanDLUT** [comment]
Dear Sir/Madam,

Thank you for your help.

If you need any other information, please let me know.

Sincerely yours,

Yan

---

Professor Yan Zhuang
School of Control Science and Engineering
Dalian University of Technology
Dalian, 116024, China
Email: zhuang@dlut.edu.cn
Tel: 86-411-84707581
Fax: 86-411-84707581

**Comment by tonystark12** [comment]
Yan,

I did not get any help. Can you please reply to the issue posted? I am not
able to understand what you are trying to say.

LN
